name: Build
on:
  workflow_dispatch: {}
  push:
    branches:
      - main
  pull_request:
    branches:
     - main
     - release/v*.*.*
jobs:
  Build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Setup Golang
        uses: actions/setup-go@v3
        with:
          go-version: 1.19.5
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Lint
        if: github.event_name == 'pull_request'
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.50.1
          only-new-issues: true
          skip-cache: true
          skip-pkg-cache: true
          skip-build-cache: true
          args: --timeout=5m
      - name: Build
        run: make build
  Tag:
    name: Tag
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request'
    permissions:
      contents: write
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Generate version
        id: generate_version
        run: echo "version=v0.1.$(date -u "+%Y%m%d-%H%M%S").$(git rev-parse --short HEAD 2>/dev/null || echo nocommitinfo)" >> $GITHUB_OUTPUT
      - name: Create Tag
        run: |
          git tag ${{steps.generate_version.outputs.version}}
          git push origin ${{steps.generate_version.outputs.version}}